[package]
name = "toy_os"
version = "0.1.0"
authors = ["ensonmj <ensonmj@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "^0.6.3"
